version: '3.4'
services:
    web-service:
      restart: always
      image: imagine10255/nginx:latest
      volumes:
        - "./config/nginx/conf.d:/etc/nginx/conf.d"
        - "./config/nginx/site-modules:/etc/nginx/site-modules"
      ports:
        - "8080:80"
        - "8443:443"
      command: [nginx-debug, '-g', 'daemon off;']



networks:
    default:
        external:
            name: imdockgroup
