version: '3.4'
services:
    web-service:
      restart: always
      image: jboesl/docker-nginx-headers-more
      container_name: imdock-nginx
      volumes:
          - "./config:/etc/nginx/conf.d"
          - "./public_html:/usr/share/nginx/html"
      ports:
          - "80:80"
          - "443:443"
      command: [nginx-debug, '-g', 'daemon off;']



networks:
    default:
        external:
            name: imdockgroup
